/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-fixed": "#ffdbcf",
        "on-tertiary": "#ffffff",
        "inverse-primary": "#ffb59c",
        "on-primary-container": "#fffbff",
        "secondary-fixed-dim": "#b8cbbb",
        "on-primary-fixed-variant": "#822801",
        "surface-dim": "#dcdad4",
        "inverse-on-surface": "#f3f1eb",
        "on-background": "#1b1c18",
        "surface-container-lowest": "#ffffff",
        "secondary-container": "#d1e5d4",
        "on-secondary-container": "#566759",
        "on-error-container": "#93000a",
        "tertiary": "#635b4f",
        "on-primary": "#ffffff",
        "surface-tint": "#a23e18",
        "outline-variant": "#dec0b7",
        "surface-bright": "#fbf9f3",
        "surface-container-low": "#f5f3ed",
        "primary": "#9f3c16",
        "on-surface-variant": "#57423b",
        "surface-container": "#f0eee8",
        "tertiary-fixed": "#ede1d1",
        "on-secondary-fixed-variant": "#3a4b3e",
        "tertiary-container": "#7d7367",
        "on-surface": "#1b1c18",
        "primary-container": "#bf542c",
        "surface-container-highest": "#e4e2dd",
        "on-secondary": "#ffffff",
        "primary-fixed-dim": "#ffb59c",
        "surface-container-high": "#eae8e2",
        "error": "#ba1a1a",
        "on-secondary-fixed": "#0f1f15",
        "surface-variant": "#e4e2dd",
        "tertiary-fixed-dim": "#d1c5b6",
        "on-error": "#ffffff",
        "outline": "#8a726a",
        "error-container": "#ffdad6",
        "secondary-fixed": "#d4e7d6",
        "on-tertiary-fixed": "#211b11",
        "on-tertiary-fixed-variant": "#4d463a",
        "on-tertiary-container": "#fffbff",
        "on-primary-fixed": "#390c00",
        "surface": "#fbf9f3",
        "inverse-surface": "#30312d",
        "background": "#fbf9f3",
        "secondary": "#516255"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "gutter": "2rem",
        "space-lg": "1.5rem",
        "gutter-mobile": "1rem",
        "margin": "3rem",
        "space-md": "1rem",
        "margin-mobile": "1.25rem",
        "space-sm": "0.5rem",
        "space-xs": "0.25rem",
        "space-xl": "2.5rem"
      },
      fontFamily: {
        "body-sm": ["Plus Jakarta Sans", "sans-serif"],
        "title-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "display-hero": ["Playfair Display", "serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Playfair Display", "serif"],
        "label-caps": ["Plus Jakarta Sans", "sans-serif"],
        "label-lg": ["Plus Jakarta Sans", "sans-serif"],
        "label-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-sm": ["Playfair Display", "serif"],
        "headline-md": ["Playfair Display", "serif"],
        "title-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg-mobile": ["Playfair Display", "serif"],
        "display-hero-mobile": ["Playfair Display", "serif"]
      },
      fontSize: {
        "body-sm": ["13px", { "lineHeight": "20px", "fontWeight": "400" }],
        "title-lg": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "display-hero": ["72px", { "lineHeight": "84px", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "body-md": ["15px", { "lineHeight": "24px", "fontWeight": "400" }],
        "headline-lg": ["44px", { "lineHeight": "54px", "letterSpacing": "-0.01em", "fontWeight": "500" }],
        "label-caps": ["11px", { "lineHeight": "16px", "letterSpacing": "0.12em", "fontWeight": "700" }],
        "label-lg": ["14px", { "lineHeight": "20px", "letterSpacing": "0.04em", "fontWeight": "600" }],
        "label-md": ["12px", { "lineHeight": "16px", "letterSpacing": "0.06em", "fontWeight": "600" }],
        "headline-sm": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "headline-md": ["32px", { "lineHeight": "40px", "fontWeight": "500" }],
        "title-md": ["16px", { "lineHeight": "24px", "fontWeight": "600" }],
        "headline-lg-mobile": ["30px", { "lineHeight": "38px", "fontWeight": "500" }],
        "display-hero-mobile": ["40px", { "lineHeight": "48px", "letterSpacing": "-0.01em", "fontWeight": "600" }]
      }
    }
  },
  plugins: [],
}
